---
# tasks file for apigee-opdk-setup-local-repository-archive
- name: Clean up any old repos
  become: true
  file:
    path: '{{ apigeerepobasepath }}/repos'
    state: absent

- name: Ensure folders exists
  become: true
  file:
    path: '{{ apigeerepobasepath }}/repos'
    state: directory

- name: Ensure rsync is present
  become: true
  yum:
    name: rsync
    state: present

- name: Copy archive to target node
  become: true
  synchronize:
    src: "{{ local_apigee_path }}/{{ apigee_archive_name }}"
    dest: "{{ apigeerepobasepath }}/{{ apigee_archive_name }}"

- name: Unarchive on target node
  unarchive:
    src: '{{ apigeerepobasepath }}/{{ apigee_archive_name }}'
    dest: '{{ apigeerepobasepath }}'
    copy: false


