---
# tasks file for apigee-opdk-setup-local-repository-archive
- name: Clean up any old repos
  become: true
  file:
    path: '{{ apigeerepobasepath }}/repos'
    state: absent

- name: Ensure repo folders exists
  become: true
  file:
    path: '{{ apigeerepobasepath }}/repos'
    state: directory
    owner: "{{ opdk_user_name }}"
    group: "{{ opdk_group_name }}"

- name: Ensure rsync is present
  become: true
  yum:
    name: rsync
    state: present

- name: Copy archive to target node
  synchronize:
    src: "{{ local_apigee_path }}/{{ apigee_archive_name }}"
    dest: "{{ apigeerepobasepath }}/{{ apigee_archive_name }}"
    owner: "{{ opdk_user_name }}"
    group: "{{ opdk_group_name }}"

- name: Unarchive on target node
  become: true
  unarchive:
    src: '{{ apigeerepobasepath }}/{{ apigee_archive_name }}'
    dest: '{{ apigeerepobasepath }}'
    copy: false
    owner: "{{ opdk_user_name }}"
    group: "{{ opdk_group_name }}"


