---
# tasks file for apigee-opdk-setup-local-repository-archive
- name: Ensure repo folders exists
  become: true
  file:
    path: '{{ apigeerepobasepath | default(opdk_installer_path) }}/repos'
    state: directory
    owner: "{{ opdk_user_name }}"
    group: "{{ opdk_group_name }}"

- name: Ensure rsync is present
  become: true
  yum:
    name: rsync
    state: present

- block:
  - name: Copy archive to target node
    become: true
    synchronize:
      src: "{{ local_apigee_path }}/{{ apigee_archive_name }}"
      dest: "{{ apigeerepobasepath | default(opdk_installer_path) }}/{{ apigee_archive_name }}"
      rsync_opts: ['--partial-dir={{ opdk_installer_path }}']
      owner: "{{ opdk_user_name }}"
      group: "{{ opdk_group_name }}"
#    register: results
#    failed_when: "'sudo: sorry, you must have a tty to run sudo' in results.stderr"
  rescue:
    - name: Copy archive to target node
      become: true
      synchronize:
        src: "{{ local_apigee_path }}/{{ apigee_archive_name }}"
        dest: "{{ apigeerepobasepath | default(opdk_installer_path) }}/{{ apigee_archive_name }}"
        rsync_opts: ['--partial-dir={{ opdk_installer_path }}']

- name: Unarchive on target node
  become: true
  unarchive:
    src: '{{ apigeerepobasepath | default(opdk_installer_path) }}/{{ apigee_archive_name }}'
    dest: '{{ apigeerepobasepath | default(opdk_installer_path) }}'
    copy: false
    owner: "{{ opdk_user_name }}"
    group: "{{ opdk_group_name }}"


