---
# tasks file for apigee-opdk-setup-local-repository-archive
- block:
  become: true
  - name: Clean up any old repos
    become: true
    file:
      path: '{{ apigeerepobasepath }}/repos'
      state: absent

  - name: Ensure folders exists
    become: true
    file:
      path: '{{ apigeerepobasepath }}/repos'
      state: directory

  - name: Install rsync if its missing
    yum:
      name: rsync
      state: present

- name: Use rsync to copy to remote node
  become: no
  synchronize:
    src: "{{ local_apigee_path }}/{{ apigee_archive_name }}"
    dest: "{{ apigeerepobasepath }}/{{ apigee_archive_name }}"

- name: Unarchive local archive to remote nodes
  unarchive:
    src: '{{ apigeerepobasepath }}/{{ apigee_archive_name }}'
    dest: '{{ apigeerepobasepath }}'
    copy: false


